#!/bin/bash
java -cp classes src.tabu.Main input/coordinates_0.txt
java -cp classes src.tabu.Main input/coordinates_1.txt
java -cp classes src.tabu.Main input/coordinates_2.txt
java -cp classes src.tabu.Main input/coordinates_3.txt
java -cp classes src.tabu.Main input/coordinates_4.txt
java -cp classes src.tabu.Main input/coordinates_5.txt
java -cp classes src.tabu.Main input/coordinates_6.txt
java -cp classes src.tabu.Main input/coordinates_7.txt
java -cp classes src.tabu.Main input/coordinates_8.txt
java -cp classes src.tabu.Main input/coordinates_9.txt
java -cp classes src.tabu.Main input/coordinates_10.txt
java -cp classes src.tabu.Main input/coordinates_11.txt
java -cp classes src.tabu.Main input/coordinates_12.txt
java -cp classes src.tabu.Main input/coordinates_13.txt
java -cp classes src.tabu.Main input/coordinates_14.txt
java -cp classes src.tabu.Main input/coordinates_15.txt
java -cp classes src.tabu.Main input/coordinates_16.txt
java -cp classes src.tabu.Main input/coordinates_17.txt
java -cp classes src.tabu.Main input/coordinates_18.txt
java -cp classes src.tabu.Main input/coordinates_19.txt
java -cp classes src.tabu.Main input/coordinates_20.txt
java -cp classes src.tabu.Main input/coordinates_21.txt
java -cp classes src.tabu.Main input/coordinates_22.txt
java -cp classes src.tabu.Main input/coordinates_23.txt
java -cp classes src.tabu.Main input/coordinates_24.txt
java -cp classes src.tabu.Main input/coordinates_25.txt
java -cp classes src.tabu.Main input/coordinates_26.txt
java -cp classes src.tabu.Main input/coordinates_27.txt
java -cp classes src.tabu.Main input/coordinates_28.txt
java -cp classes src.tabu.Main input/coordinates_29.txt
java -cp classes src.tabu.Main input/coordinates_30.txt
java -cp classes src.tabu.Main input/coordinates_31.txt
java -cp classes src.tabu.Main input/coordinates_32.txt
java -cp classes src.tabu.Main input/coordinates_33.txt
java -cp classes src.tabu.Main input/coordinates_34.txt
java -cp classes src.tabu.Main input/coordinates_35.txt
java -cp classes src.tabu.Main input/coordinates_36.txt
java -cp classes src.tabu.Main input/coordinates_37.txt
java -cp classes src.tabu.Main input/coordinates_38.txt
java -cp classes src.tabu.Main input/coordinates_39.txt
java -cp classes src.tabu.Main input/coordinates_40.txt
java -cp classes src.tabu.Main input/coordinates_41.txt
java -cp classes src.tabu.Main input/coordinates_42.txt
java -cp classes src.tabu.Main input/coordinates_43.txt
java -cp classes src.tabu.Main input/coordinates_44.txt
java -cp classes src.tabu.Main input/coordinates_45.txt
java -cp classes src.tabu.Main input/coordinates_46.txt
java -cp classes src.tabu.Main input/coordinates_47.txt
java -cp classes src.tabu.Main input/coordinates_48.txt
java -cp classes src.tabu.Main input/coordinates_49.txt
